name: Build & Deploy Hugo Site

on:
  push:
    branches: ["main", "hugo_build"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.0'

      - name: Install Hugo CLI
        env:
          HUGO_VERSION: 0.148.2
        run: |
          wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
          && sudo dpkg -i ${{ runner.temp }}/hugo.deb

      - name: Clear Hugo cache
        run: hugo mod clean

      - name: Install Hugo modules
        run: hugo mod get

      - name: Build Hugo site
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
        run: |
          hugo --minify --baseURL="https://azajmahmud.github.io/demo_website/"

      # Upload public folder as Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public

deploy:
  needs: build
  runs-on: ubuntu-latest
  environment:
    name: github-pages
    url: https://azajmahmud.github.io/demo_website/
  steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
